added following features:-
NotiFair/Backend pull request #3
Opened 2023-05-04 09:26 UTC by raxkumar

1) added user CRUD
2) added Exception handling

2023-05-04 10:30 UTC, rohithteja95 requested changes

2023-05-04 10:30 UTC, rohithteja95 commented on user/src/main/java/com/notifity/backend/user/aop/logging/LoggingAspect.java
> +  //    }
Why is this causing an issue?

2023-05-04 10:30 UTC, rohithteja95 commented on user/src/main/java/com/notifity/backend/user/domain/User.java
> +@Document(collection = "user")
it is a collection of users right, so collection can be renamed as users, instead of user.

2023-05-04 10:30 UTC, rohithteja95 commented on user/src/main/java/com/notifity/backend/user/domain/User.java
> +  @Indexed(unique = true)
first name alone need not be unique.
let us discuss and create compound indices after we start building logic.
you can remove this index.

2023-05-04 13:59 UTC, raxkumar commented on user/src/main/java/com/notifity/backend/user/aop/logging/LoggingAspect.java
> +  //    }
will look into it

2023-05-06 14:16 UTC, rohithteja95 approved these changes

2023-05-08 19:00 UTC, merged